In [19]:
import json

In [20]:
file_name = 'hockeyscrape/canes.json'

In [21]:
with open(file_name) as fp:
    hockey_json = json.load(fp)

In [22]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [23]:
hockey_df = pd.DataFrame(hockey_json)

In [24]:
hockey_df.head()

,year,date_game,game_location,opp_name,goals,opp_goals,game_outcome,overtimes,shots,pen_min,goals_pp,chances_pp,goals_sh,shots_against,pen_min_opp,goals_against_pp,opp_chances_pp,goals_against_sh,corsi_for,corsi_against,corsi_pct,fenwick_for,fenwick_against,fenwick_pct,faceoff_wins,faceoff_losses,faceoff_percentage,zs_offense_pct,pdo
0,1998,1997-10-01,@,Tampa Bay Lightning,2,4,L,,29,39,1,,0,27,39,2,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1998,1997-10-03,,Pittsburgh Penguins,3,4,L,,28,72,2,,0,27,43,1,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1998,1997-10-04,@,Ottawa Senators,2,3,L,,18,16,1,,0,27,10,2,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,1997-10-07,,Los Angeles Kings,3,3,T,OT,29,18,0,,0,30,10,0,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1998,1997-10-10,,New Jersey Devils,2,1,W,,27,8,0,,0,17,8,0,,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
def convert_game_location(loc):
    if loc == '@':
        return 'A'
    return 'H'

In [26]:
hockey_df['game_location'] = hockey_df['game_location'].apply(convert_game_location)

In [27]:
hockey_df = hockey_df.fillna(value='')

In [28]:
hockey_df.describe()

,year,date_game,game_location,opp_name,goals,opp_goals,game_outcome,overtimes,shots,pen_min,goals_pp,chances_pp,goals_sh,shots_against,pen_min_opp,goals_against_pp,opp_chances_pp,goals_against_sh,corsi_for,corsi_against,corsi_pct,fenwick_for,fenwick_against,fenwick_pct,faceoff_wins,faceoff_losses,faceoff_percentage,zs_offense_pct,pdo
count,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876,1876
unique,21,1784,2,33,11,11,4,5,47,51,7,11,5,46,58,7,9,5,66,60,298,55,49,306,38,37,253,375,320
top,2006,2000-02-19,H,Washington Capitals,2,3,L,,28,6,0,,0,25,6,0,,0,,,,,,,,,,,
freq,114,2,940,126,444,448,929,1449,124,280,956,1515,1715,119,273,896,1515,1610,931,931,931,931,929,931,929,929,931,931,931

In [29]:
hockey_df

,year,date_game,game_location,opp_name,goals,opp_goals,game_outcome,overtimes,shots,pen_min,goals_pp,chances_pp,goals_sh,shots_against,pen_min_opp,goals_against_pp,opp_chances_pp,goals_against_sh,corsi_for,corsi_against,corsi_pct,fenwick_for,fenwick_against,fenwick_pct,faceoff_wins,faceoff_losses,faceoff_percentage,zs_offense_pct,pdo
0,1998,1997-10-01,A,Tampa Bay Lightning,2,4,L,,29,39,1,,0,27,39,2,,0,,,,,,,,,,,
1,1998,1997-10-03,H,Pittsburgh Penguins,3,4,L,,28,72,2,,0,27,43,1,,0,,,,,,,,,,,
2,1998,1997-10-04,A,Ottawa Senators,2,3,L,,18,16,1,,0,27,10,2,,0,,,,,,,,,,,
3,1998,1997-10-07,H,Los Angeles Kings,3,3,T,OT,29,18,0,,0,30,10,0,,0,,,,,,,,,,,
4,1998,1997-10-10,H,New Jersey Devils,2,1,W,,27,8,0,,0,17,8,0,,0,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,2019,2019-05-12,A,Boston Bruins,2,6,L,,23,4,0,4,0,25,8,2,2,0,31,32,49.2,24,25,49.0,17,22,43.6,45.5,91.4
1872,2009,2009-05-23,H,Pittsburgh Penguins,2,6,L,,34,10,0,,0,40,8,2,,0,63,57,52.5,44,45,49.4,21,22,48.8,39.5,96.0
1873,2019,2019-05-14,H,Boston Bruins,1,2,L,,36,14,0,5,0,31,14,1,5,0,48,41,53.9,34,30,53.1,19,26,42.2,60.2,99.8
1874,2009,2009-05-26,H,Pittsburgh Penguins,1,4,L,,31,10,0,,0,25,8,0,,0,55,33,62.5,38,24,61.3,20,21,48.8,75.0,80.6
1875,2019,2019-05-16,H,Boston Bruins,0,4,L,,24,6,0,2,0,23,4,2,3,0,58,44,56.9,35,29,54.7,28,29,49.1,56.0,88.2

In [30]:
out_name = 'canes.csv'

In [31]:
hockey_df.to_csv(out_name,index=False)